name: React Checks

on:
  [pull_request]

jobs:
  checks_react_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: ${{ github.head_ref }}
          VALIDATE_ALL_CODEBASE: false
          FILTER_REGEX_INCLUDE: .*client/.*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Next js app
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - working-directory: ./client
        run: npm ci
      - working-directory: ./client
        run: npm run build

